### ISSUE TITLE
Incorrect image filename for marvelcdb

### ISSUE THREAD

**Issue by mindblink** [OliBus801/CardGames#1]
image files do not correspond to to marvelcdb.com's downloaded Txt file. This fixes the blank imported images.	

Needed
renamed:    Make_The_Call.png -> Make_the_Call.png
renamed:    Strength_in_Numbers.png -> Strength_In_Numbers.png

**Comment by OliBus801** [comment]
Hey ! I had no idea anybody was actually using my repository !

Sorry for the huge delay, I started college and I haven't maintained this repository ! 
I fixed the issues, thanks for spotting them :-)
